spring.application.name=Ticketeo
spring.datasource.url=jdbc:postgresql://localhost:5432/TicketeoDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false

spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN

# Upload limits for event images
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB
spring.servlet.multipart.resolve-lazily=true
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-part-count=-1
server.tomcat.max-parameter-count=-1